name: beats_remake
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/home/modul/
    - assets/images/home/shortcut_icon/
    - assets/images/home/appbar_icon/
    - assets/images/login/
    - assets/images/splash_screen/
    - assets/images/navigation/
    - assets/images/be_campaign/
    - assets/images/beats_point/
    - assets/images/task_list/
    - assets/images/beats_id/
    - assets/images/beats_id/icons/
    - assets/images/beats_id/page_inside/
  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
